{% set name = "PyCO2SYS" %}
{% set version = "1.8.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyCO2SYS-{{ version }}.tar.gz
  sha256: 6b816d1e89faf435fbf194ad6b653d3ad1a6526046815c3162c04352d7a0e3e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - autograd
    - numpy <2

test:
  imports:
    - PyCO2SYS
  commands:
    - pip check
  requires:
    - pip

about:
  summary: 'PyCO2SYS: marine carbonate system calculations in Python'
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/PyCO2SYS

extra:
  recipe-maintainers:
    - mvdh7
