{% set name = "PyCO2SYS" %}
{% set version = "1.8.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyCO2SYS-{{ version }}.tar.gz
  sha256: eeb622f05bedfc6d4cb7fe757ec75bd779619da0b7560bbe83efce1dbf99bcce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - autograd
    - numpy

test:
  imports:
    - PyCO2SYS
  commands:
    - pip check
  requires:
    - pip

about:
  summary: 'PyCO2SYS: marine carbonate system calculations in Python'
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/PyCO2SYS

extra:
  recipe-maintainers:
    - mvdh7
