{% set name = "PyCO2SYS" %}
{% set version = "1.8.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyco2sys-{{ version }}.tar.gz
  sha256: a75d94b59e1bdd9e64d33b2c475b382862badda5e45d4c9e271ec95bdbb42c2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - autograd
    - numpy

test:
  imports:
    - PyCO2SYS
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'PyCO2SYS: marine carbonate system calculations in Python'
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/PyCO2SYS

extra:
  recipe-maintainers:
    - mvdh7
